{{- $imageAutonity := .Values.imageAutonity -}}
{{- $imageAutonity_init := .Values.imageAutonity_init -}}
{{- $imageNginx := .Values.image_nginx -}}
{{- $namespace := .Release.Namespace -}}
{{- $releasename := .Release.Name -}}
{{- $httpRpcEnabled := .Values.http_rpc.enabled -}}
{{- $httpRpcAddress := .Values.http_rpc.address -}}
{{- $httpRpcPort := .Values.http_rpc.port -}}
{{- $httpRpcApi := .Values.http_rpc.api -}}
{{- $httpRpcVhosts := .Values.http_rpc.vhosts -}}
{{- $wsRpcEnabled := .Values.ws_rpc.enabled -}}
{{- $wsRpcAddress := .Values.ws_rpc.address -}}
{{- $wsRpcPort := .Values.ws_rpc.port -}}
{{- $wsRpcApi := .Values.ws_rpc.api -}}
{{- $wsRpcOrigins := .Values.ws_rpc.origins -}}
{{- $debugEnabled := .Values.debug_enabled -}}
{{- $loggingVerbosity := .Values.logging_verbosity -}}
{{- $pprofEnabled := .Values.pprof.enabled -}}
{{- $pprofAddress := .Values.pprof.address -}}
{{- $pprofPort := .Values.pprof.port -}}
{{- $graphqlEnabled := .Values.graphql_enabled -}}
{{- $networkid :=  .Values.networkid -}}
{{- $ethstatsEnabled :=  .Values.global.ethstats.enabled -}}
{{- $rpcHttpBasicAuthEnabled :=  .Values.rpc_http_basic_auth_enabled -}}
{{- $rpcHttpsEnabled :=  .Values.rpc_https_enabled -}}
{{- $awsPersistentStorageEnabled :=  .Values.aws_persistent_storage_enabled -}}
{{- $gcpPersistentStorageEnabled :=  .Values.gcp_persistent_storage_enabled -}}

{{ range $i, $e := until (atoi (toString .Values.observers.num)) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: observer-{{ $i }}
  namespace: {{ $namespace }}
spec:
  selector:
    matchLabels:
        app: observer-{{ $i }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: observer-{{ $i }}
    spec:
      initContainers:
      - name: init
        image: {{ $imageAutonity_init.repository }}:{{ $imageAutonity_init.tag }}
        volumeMounts:
        - name: blockchain
          mountPath: /autonity/blockchain
        - name: keys
          mountPath: /autonity/keys
        - name: cm-genesis
          mountPath: /autonity/cm-genesis
        - name: sec-account-pwd
          mountPath: /autonity/sec-account-pwd
        - name: sec-peers
          mountPath: /autonity/sec-peers
      containers:
      - name: autonity
        image: {{ $imageAutonity.repository }}:{{ $imageAutonity.tag }}
        ports:
        - containerPort: 30303
          name: p2p
        args:
          - "--datadir"
          - "/autonity/blockchain"
          - "--keystore"
          - "/autonity/keys/keystore"
          - "--nodekey"
          - "/autonity/sec-peers/private_key"
          - "--gcmode"
          - "archive"
          - "--syncmode"
          - "full"
          - "--cache"
          - "1024"
{{ if eq $httpRpcEnabled true }}
          - "--http"
          - "--http.addr"
          - "{{ $httpRpcAddress }}"
          - "--http.port"
          - "{{ $httpRpcPort }}"
          - "--http.api"
          - "{{ $httpRpcApi }}"
          - "--http.vhosts"
          - "{{ $httpRpcVhosts }}"
{{ end }}
{{ if eq $wsRpcEnabled true }}
          - "--ws"
          - "--ws.addr"
          - "{{ $wsRpcAddress }}"
          - "--ws.port"
          - "{{ $wsRpcPort }}"
          - "--ws.api"
          - "{{ $wsRpcApi }}"
          - "--ws.origins"
          - "{{ $wsRpcOrigins }}"
{{ end }}
          - "--metrics"
          - "--networkid"
          - "{{ $networkid }}"
{{ if eq $debugEnabled true }}
          - "--debug"
{{ end }}
          - "--verbosity"
          - "{{ $loggingVerbosity }}"
{{ if eq $pprofEnabled true }}
          - "--pprof"
          - "--pprof.addr"
          - "{{ $pprofAddress }}"
          - "--pprof.port"
          - "{{ $pprofPort }}"
{{ end }}
{{ if eq $graphqlEnabled true }}
          - "--graphql"
{{ end }}
          - "--nousb"
{{ if $ethstatsEnabled }}
          - "--ethstats"
          - "observer-{{ $i }}:$(ETHSTATS_SECRET)@ethstats.{{ $namespace }}"
        env:
        - name: ETHSTATS_SECRET
          valueFrom:
            secretKeyRef:
              name: ethstats
              key: WS_SECRET
{{ end }}
        volumeMounts:
        - name: blockchain
          mountPath: /autonity/blockchain
        - name: keys
          mountPath: /autonity/keys
        - name: sec-peers
          mountPath: /autonity/sec-peers
      - name: nginx
        image: {{ $imageNginx.repository }}:{{ $imageNginx.tag }}
        ports:
        - containerPort: 8080
          name: https-rpc
        volumeMounts:
        - name: nginx-proxy-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
{{ if $rpcHttpBasicAuthEnabled }}
        - name: nginx-proxy-config
          mountPath: /etc/nginx/htpasswd
          subPath: htpasswd
{{ end }}
{{ if $rpcHttpsEnabled }}
        - name: nginx-proxy-ssl
          mountPath: /etc/nginx/ssl
{{ end }}
      volumes:
        - name: blockchain
{{ if or (eq $awsPersistentStorageEnabled true) (eq $gcpPersistentStorageEnabled true)}}
          persistentVolumeClaim:
            claimName: {{ $releasename }}-observer-{{ $i }}-blockchain
{{ else }}
          emptyDir: {}
{{ end}}
        - name: keys
          emptyDir:
            medium: Memory
            sizeLimit: "1M"
        - name: cm-genesis
          configMap:
            name: genesis
        - name: sec-account-pwd
          secret:
            secretName: account-pwd
        - name: sec-peers
          secret:
            secretName: observers
            items:
              - key: {{ $i }}.private_key
                path: private_key
        - name: nginx-proxy-config
          configMap:
            name: nginx-conf
{{ if $rpcHttpsEnabled }}
        - name: nginx-proxy-ssl
          secret:
            secretName: autonity-https
{{ end }}
{{- end}}
